### PR TITLE
Testing: Landing Page

### PR DESCRIPTION
**Pull request by onepeso**
# Description
**Testing the landing page.**

## Change Status

- [X] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [X] Test A

# Checklist

- [X] I have performed a self-review of my own code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Comment by onepeso** [comment]
[Create Tests for the Landing Page](https://trello.com/c/sDkLZSmy/50-create-tests-for-the-landing-page)

**Comment by onepeso** [comment]
[Create Tests for the Landing Page](https://trello.com/c/sDkLZSmy/50-create-tests-for-the-landing-page)

**Review by Rrawla2 — APPROVED** [review]
Looks great.  Glad the testing is fixed!

**Review by jess-lam — APPROVED** [review]
Nice job!

**Pull request merged**
