### PR TITLE
Update 0.2: Dashboard 

### PR DESCRIPTION
**Pull request by onepeso**
# Description
This update will bring a bunch of updates to the dashboard I am going to be working on. Below you can view the updates that are being worked on:

- Dashboard General Fixes 
   - Dashboard Welcome Message - Add random quotes to the welcoming page. This will provide users with quotes to give them some motivational reasoning to continue their exercise journey. 
- Dashboard Styling
  - Fixed CreateWorkout.js styling to be more responsive in desktop mode.
  - Fixed Dashboard Navigation System Design to be Mobile to Desktop. 
  - Fixed Dashboard Navigation System from position being none to position being sticky. This helps ensure that the height of the navigation bar doesn't run out of height. 
  - Made logo inside the Dashboard Navigation Bar send you back to the dashboard welcome page.
  - Fixed CreateWorkoutForm not being responsive to responsive. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, but not tested (may need new tests)

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by onepeso** [comment]
[Styling Dashboard](https://trello.com/c/Y9aok0z8/57-styling-dashboard)

**Review by Rrawla2 — APPROVED** [review]
Awesome. I was going to ask you if you wanted the logo to go back to the dashboard too!

**Comment by onepeso** [comment]
> Awesome. I was going to ask you if you wanted the logo to go back to the dashboard too!

I just thought about it today :)

**Review by ConfusionOrb221 — APPROVED** [review]
Looks Nice

**Pull request merged**
