### PR TITLE
Quick update on the README file

### PR DESCRIPTION
**Pull request by onepeso**
# Description
_Updated the team images to be current. Fixed some links that were out of date._ 

Fixes # (quick update)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] ReadMe Change

## Change Status

- [ ] Complete, tested, ready to review and merge
- [X] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by TheNativeDev — APPROVED** [review]
Thank you for updating this

**Comment by onepeso** [comment]
@jess-lam can you please review this?

**Review by jess-lam — APPROVED** [review]
Looks great!

**Comment by onepeso** [comment]
[Update README](https://trello.com/c/MmvPWU48/3-update-readme)

**Pull request merged**
