### PR TITLE
Addition: Set Up for Primer Design System

### PR DESCRIPTION
**Pull request by onepeso**
…ndencies

# Description
Quick addition of a dependency for Primer Design System

Fixes # (addition only)

## Type of change
added dependency + updated other dependencies 

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [X] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Review by TheNativeDev — APPROVED** [review]
looks good

**Comment by onepeso** [comment]
@jess-lam or @Rrawla2 Could you please look at this simple PR to practice approving and commenting. It is a simple PR just adding Primer to our Dependencies.

**Review by Rrawla2 — APPROVED** [review]
Good job! Get rid of Yup next time.

**Comment by onepeso** [comment]
> Good job! Get rid of Yup next time.

Sounds good! Thank you!

**Comment by onepeso** [comment]
[Add Primer Design System Dependency](https://trello.com/c/HiCyaEbm/32-add-primer-design-system-dependency)

**Pull request merged**
